CREATE TABLE students (

    id INT AUTO_INCREMENT PRIMARY KEY,

    fullname VARCHAR(100) NOT NULL,

    dob DATE NOT NULL,

    institution VARCHAR(150) NOT NULL,

    phone VARCHAR(20) NOT NULL,

    email VARCHAR(100) UNIQUE NOT NULL,

    class_year VARCHAR(100) NOT NULL,

    date_registered TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
